source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SMBCustomRelationshipSegue_Example', :exclusive => true do
  pod "SMBCustomRelationshipSegue", :path => "../"
  pod 'RESideMenu'
end

target 'SMBCustomRelationshipSegue_Tests', :exclusive => true do
  pod "SMBCustomRelationshipSegue", :path => "../"

  
end
